name: qazi9amaan/formlibrary
on:
  push:
    branches:
      - 'master' 
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # When setting up node:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          git config --global user.name 'Automated publish'
          git config --global user.email 'qazi9amaan@gmail.com'
      # Build and publish:
      - run: npm install
      - run: npm build:lib
      - run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
